- name: purge firewalls
  apt: name={{ item }} state=absent purge=yes
  with_items:
#    - apparmor
#    - apparmor-utils
    - ufw
- name: install basic packages
  apt: name={{ item }} state=latest update_cache=yes cache_valid_time=43200
  with_items:
    - curl
    - htop
    - vim-nox
    - iperf
