---
- hosts: all
  roles:
    - common

- hosts: multicast
  roles:
    - multicast

- hosts: docker
  roles:
    - docker

- hosts: postgres
  tasks:
  - name: run postgres container
    docker: >
      image=postgres
      name=postgres
      ports=5432:5432
      env='POSTGRES_PASSWORD=postgres'

- hosts: amqp
  tasks:
  - name: run rabbitmq container
    docker: >
      image=tutum/rabbitmq
      name=rabbitmq
      ports=5672:5672,15672:15672
      env='RABBITMQ_PASS=admin'

- hosts: redis
  tasks:
  - name: run redis container
    docker: >
      image=redis
      name=redis
      ports=6379:6379

- hosts: mongo
  tasks:
  - name: run mongo container
    docker: >
      image=dockerfile/mongodb
      name=mongodb
      ports=27017:27017,28017:28017
      command='mongod --rest --httpinterface'

- hosts: mysql
  tasks:
  - name: run sql container
    docker: >
      image=mysql
      ports=3306:3306
      env='MYSQL_ROOT_PASSWORD=root'

- hosts: graphite
  tasks:
  - name: run graphite and statsd
    docker: >
      name=graphite
      image=hopsoft/graphite-statsd
      ports=80:80,2003:2003,8125:8125/udp

- hosts: storm
  tasks:
  - name: run zookeeper
    docker: >
      image=wurstmeister/zookeeper
      name=zookeeper
      ports=2181:2181
  - name: run storm nimbus
    docker: >
      image=wurstmeister/storm-nimbus
      name=nimbus
      ports=3773:3773,3772:3772,6627:6627
      links=zookeeper:zk
  - name: run storm supervisor
    docker: >
      image=wurstmeister/storm-supervisor
      name=supervisor
      ports=8000:8000
      links=nimbus:nimbus,zookeeper:zk
  - name: run storm ui
    docker: >
      image=wurstmeister/storm-ui
      name=ui
      ports=8080:8080
      links=nimbus:nimbus,zookeeper:zk
